### ISSUE TITLE
Errors when solution has only solution folders as root elements

### ISSUE THREAD

**Issue by mozts2005** [ilchenkob/dto-writer#1]
using visual studio Enterprise 15.7.6 on Windows 10 build 1803

When calling the context menu option in a solution where every project is in a solution folder I receive an error message. 

![image](https://user-images.githubusercontent.com/626061/43913636-dc5bc58c-9bc2-11e8-8a8b-d05a9d4c4f70.png)

When I do the same and the projects are not in a solution folder everything works fine.

**Comment by ilchenkob** [comment]
@mozts2005 
Thank you for your feedback.
This issue is already solved in version 2.5 (and it's already available in VS Marketplace)

**Comment by mozts2005** [comment]
Thanks
